### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by mcbenjemaa** [luthermonson/go-proxmox#138]
I think It's time to plan for the first release v0.1.0

**Comment by luthermonson** [comment]
i think we're there too, the core marshalling bits have been super stable since adding context and we're just adding types and endpoint funcs. let me spend some time getting some last minute things merged and I'll leave this up and post it in the slack to see if anyone has any opinions if we are missing something for a v0.1.0 release

**Comment by justinclift** [comment]
Before creating a 0.1.0 release, it's probably a good idea to add some super basic "intro" documentation to the README:

* How to create a new VM and delete it
* Same, but for containers

Those are the most likely tasks people would be starting with, so they should be covered and explained.

Saying that because it was a pita to find the `NewVirtualMachine()` function (via guessing keywords), and the existing documentation is a bit on the sparse side: :wink:

![image](https://github.com/luthermonson/go-proxmox/assets/406299/ec9de97b-e820-4285-93ea-d8243f535173)

**Comment by luthermonson** [comment]
Ya good point

**Comment by mcbenjemaa** [comment]
is this ready to proceed with the release?
we need it as part of https://github.com/ionos-cloud/cluster-api-provider-proxmox/issues/225

**Comment by wikkyk** [comment]
Is there something we (@mcbenjemaa and I) could do to help?

**Comment by luthermonson** [comment]
ah no sorry... i just forgot. ill do it now

**Comment by luthermonson** [comment]
https://github.com/luthermonson/go-proxmox/releases/tag/v0.1.0

here you go!

**Comment by luthermonson** [comment]
will work on some documentation when i get some time to work on this again

**Comment by justinclift** [comment]
To me, it feels like the upstream Proxmox API needs to add the ability import disk images before any of the language specific API projects (like go-proxmox) will be super useful.

**Comment by wikkyk** [comment]
@justinclift You could hack it together with ISOs and cloud-init but that'll never be quite as nice as just dumping a disc image :(

**Comment by wikkyk** [comment]
https://github.com/ionos-cloud/cluster-api-provider-proxmox/pull/246 Thanks!
